# -*- coding: utf-8 -*-
"""PDF report generation using FPDF2."""

import os
from datetime import datetime
from fpdf import FPDF
import pandas as pd
from PIL import Image


class PDFReport(FPDF):
    """Professional stock research report PDF."""

    def __init__(self, company: str, ticker: str, **kwargs):
        super().__init__(**kwargs)
        self._company = self._sanitize(company)
        self._ticker = self._sanitize(ticker)

    def _sanitize(self, text: str) -> str:
        """Replace unsupported characters with Latin-1 equivalents."""
        if not isinstance(text, str):
            return str(text)
        replacements = {
            "’": "'", "‘": "'", "“": '"', "”": '"', "–": "-", "—": "-",
            "…": "...", "•": "-", "✔": "YES", "✘": "NO"
        }
        for k, v in replacements.items():
            text = text.replace(k, v)
        return text.encode("latin-1", "replace").decode("latin-1")

    def header(self):
        self.set_font("Arial", "B", 8)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, f"Stock Report: {self._company} ({self._ticker})", align="L")
        self.cell(0, 10, f"Date: {datetime.now().strftime('%Y-%m-%d')}", ln=True, align="R")
        self.set_draw_color(0, 212, 170)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 7)
        self.set_text_color(130, 130, 130)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} | Generated by Stock AI Agent", align="C")

    def section_title(self, title, style="B", size=13, ln=3, align="L"):
        self.set_font("Arial", style, size)
        self.set_text_color(30, 30, 30)
        self.cell(0, 8, title, ln=True, align=align)
        if style == "B" and size >= 12:
            self.set_draw_color(0, 212, 170)
            self.line(self.get_x(), self.get_y(), self.get_x() + 40, self.get_y())
        self.ln(ln)

    def section_body(self, text, style="", size=10, h=5):
        self.set_font("Arial", style, size)
        self.set_text_color(60, 60, 60)
        # Clean markdown formatting and sanitize
        text = str(text)
        text = text.replace("**", "").replace("##", "").replace("###", "")
        text = self._sanitize(text)
        self.multi_cell(0, h, text)
        self.ln(3)

    def add_dataframe(self, dataframe: pd.DataFrame):
        if dataframe.empty:
            self.section_body("No data available.", "I", 9)
            return

        self.set_font("Times", size=7)
        col_widths = []
        for col in dataframe.columns:
            max_w = self.get_string_width(str(col))
            for item in dataframe[col]:
                max_w = max(max_w, self.get_string_width(str(item)))
            col_widths.append(min(max_w + 5, 35))

        total_w = sum(col_widths)
        if total_w > 190:
            scale = 190 / total_w
            col_widths = [w * scale for w in col_widths]

        th = self.font_size + 2
        x0 = self.get_x()

        # Header
        self.set_draw_color(0, 212, 170)
        self.line(x0, self.get_y(), x0 + sum(col_widths), self.get_y())
        self.set_font("Times", "B", 7)
        self.set_text_color(30, 30, 30)
        for i, col in enumerate(dataframe.columns):
            self.cell(col_widths[i], th, str(col)[:15], border=0)
        self.ln(th)
        self.line(x0, self.get_y(), x0 + sum(col_widths), self.get_y())

        # Rows
        self.set_font("Times", "", 7)
        self.set_text_color(60, 60, 60)
        for idx in range(len(dataframe)):
            if self.get_y() > 270:
                self.add_page()
            for j, item in enumerate(dataframe.iloc[idx]):
                self.cell(col_widths[j], th, str(item)[:18], border=0)
            self.ln(th)

        self.line(x0, self.get_y(), x0 + sum(col_widths), self.get_y())
        self.ln(3)

    def add_image_safe(self, path: str, w: int = 125, center: bool = True):
        """Add an image if it exists."""
        if os.path.exists(path):
            try:
                x = (210 - w) / 2 if center else self.get_x()
                if self.get_y() + 80 > 270:
                    self.add_page()
                self.image(path, w=w, x=x)
                self.ln(6)
            except Exception:
                pass


def generate_report(
    ticker: str,
    overview: dict,
    results: dict,
    df_results: dict,
    conclusion: str,
    statements: dict,
    chart_paths: list | None = None,
) -> str:
    """Generate the full PDF report and return the file path."""

    company = overview.get("name", ticker)
    instrument_type = overview.get("instrument_type", "Stock")

    pdf = PDFReport(company, ticker)
    pdf.alias_nb_pages()
    pdf.add_page()

    # ── Cover / Header ──
    pdf.section_title(company, size=18, ln=5, align="C")
    pdf.section_title(f"Ticker: {ticker} | Type: {instrument_type}", "I", 9, ln=1, align="C")
    pdf.section_title(f"Price: ${overview.get('price', 'N/A')}", "I", 9, ln=1, align="C")

    if instrument_type in ("Stock", "REIT"):
        pdf.section_title(
            f"Sector: {overview.get('sector', 'N/A')} | Industry: {overview.get('industry', 'N/A')}",
            "I", 8, ln=4, align="C",
        )
    else:
        pdf.section_title(
            f"Category: {overview.get('category', 'N/A')}",
            "I", 8, ln=4, align="C",
        )

    desc = overview.get("description", "")
    if desc:
        pdf.section_body(desc[:1500], "I", 8, 4)

    # ── News Overview ──
    if "news" in results:
        pdf.section_title("Market & News Overview")
        pdf.section_body(results["news"])

    # ── Valuation ──
    if "valuation" in results:
        pdf.section_title("Valuation Analysis")
        pdf.section_body(results["valuation"])

    # ── Financial Statements (stocks only) ──
    if instrument_type in ("Stock", "REIT") and statements:
        pdf.add_page()
        pdf.section_title("Financial Statements")

        for label, key in [("Income Statement", "income"), ("Balance Sheet", "balance"), ("Cash Flow", "cashflow")]:
            if key in statements and not statements[key].empty:
                pdf.section_title(label, "BI", 10, ln=2)
                pdf.add_dataframe(statements[key])
                if key in df_results:
                    pdf.section_body(df_results[key])

    # ── ETF Holdings ──
    if instrument_type == "ETF" and "etf" in results:
        pdf.add_page()
        pdf.section_title("ETF Analysis")
        pdf.section_body(results["etf"])

    # ── Fundamentals ──
    if "fundamentals" in results:
        pdf.section_title("Fundamental Analysis")
        pdf.section_body(results["fundamentals"])

    # ── Risk Metrics ──
    if "risk" in results:
        pdf.section_title("Risk Analysis")
        pdf.section_body(results["risk"])

    # ── Monte Carlo ──
    if "montecarlo" in results:
        pdf.section_title("Monte Carlo Simulation")
        pdf.section_body(results["montecarlo"])

    # ── Options ──
    if "options" in results:
        pdf.section_title("Options Analysis")
        pdf.section_body(results["options"])

    # ── Charts ──
    if chart_paths:
        pdf.add_page()
        pdf.section_title("Charts & Technical Analysis")
        for path in chart_paths:
            pdf.add_image_safe(path)

    if "technicals" in results:
        pdf.section_body(results["technicals"])

    # ── Conclusion ──
    pdf.add_page()
    pdf.section_title("Investment Conclusion", size=14)
    pdf.section_body(conclusion)

    # Save
    filename = f"{ticker}_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    pdf.output(filename)
    return filename
